export const json = [
  {
    type: "Vivienda",
    address: "Av Jujuy 1400",
    spaces: 2,
    price: 184.0,
    pictures: [
      {
        img: "https://static.tokkobroker.com/water_pics/14907697653197652569051686380877645231979661584017716880739567280369382006832.jpg",
      },
      {
        img: "https://static.tokkobroker.com/water_pics/35586777785092755108429238162592047584634765320319728803520720336782775320809.jpg",
      },
      {
        img: "https://static.tokkobroker.com/water_pics/112148084975145032558414398193639620330075218899527775609330788039478128584754.jpg",
      },
    ],
    floors: 10,
    covered_area: 37,
    bathroom: 1.5,
    bedroom: 1,
    furnished: true,
    description:
      "DPTO. 2 AMBIENTES, CFTE., BALCON,  APTO PROFESIONAL, AMENITIES, A ESTRENAR, ENTREGA INMEDIATA!",
    situation: "Disponible",
    total_area: 40,
    antiquity: 1,
    operation: "Alquiler",
    owner: "Schiaffino",
  },
  {
    type: "Vivienda",
    address: "RIO NEGRO NO SE CUANTO",
    spaces: 2,
    price: 94.0,
    pictures: [
      {
        img: "https://static.tokkobroker.com/water_pics/61473490849556420478476952427662215243829091586321796539503166833583826460719.jpg",
      },
    ],
    floors: 10,
    covered_area: 37,
    bathroom: 1.5,
    bedroom: 1,
    furnished: true,
    description:
      "DPTO. 2 AMBIENTES, CFTE., BALCON,  APTO PROFESIONAL, AMENITIES, A ESTRENAR, ENTREGA INMEDIATA!",
    situation: "Disponible",

    total_area: 40,
    antiquity: 1,
    operation: "Alquiler",
    owner: "Schiaffino",
  },
  {
    type: "Vivienda",
    address: "CONGRESO Y NO SE CUAL MAS",
    spaces: 2,
    price: 82.0,
    pictures: [
      {
        img: "https://static.tokkobroker.com/water_pics/61473490849556420478476952427662215243829091586321796539503166833583826460719.jpg",
      },
    ],
    floors: 10,
    covered_area: 37,
    bathroom: 1.5,
    bedroom: 1,
    furnished: true,
    description:
      "DPTO. 2 AMBIENTES, CFTE., BALCON,  APTO PROFESIONAL, AMENITIES, A ESTRENAR, ENTREGA INMEDIATA!",
    situation: "Disponible",

    total_area: 40,
    antiquity: 1,
    operation: "Venta",
    owner: "Schiaffino",
  },
  {
    type: "Local",
    address: "NUEVA YORK 1230",
    spaces: 2,
    price: 33.0,
    pictures: [
      {
        img: "https://static.tokkobroker.com/water_pics/61473490849556420478476952427662215243829091586321796539503166833583826460719.jpg",
      },
    ],
    floors: 10,
    covered_area: 37,
    bathroom: 1.5,
    bedroom: 1,
    furnished: true,
    description:
      "DPTO. 2 AMBIENTES, CFTE., BALCON,  APTO PROFESIONAL, AMENITIES, A ESTRENAR, ENTREGA INMEDIATA!",
    situation: "Disponible",

    total_area: 40,
    antiquity: 1,
    operation: "Alquiler",
    owner: "Schiaffino",
  },
  {
    type: "Local",
    address: "SENILLOSA ALGUN NUMERO",
    spaces: 2,
    price: 76.0,
    pictures: [
      {
        img: "https://static.tokkobroker.com/water_pics/61473490849556420478476952427662215243829091586321796539503166833583826460719.jpg",
      },
    ],
    floors: 10,
    covered_area: 37,
    bathroom: 1.5,
    bedroom: 1,
    furnished: true,
    description:
      "DPTO. 2 AMBIENTES, CFTE., BALCON,  APTO PROFESIONAL, AMENITIES, A ESTRENAR, ENTREGA INMEDIATA!",
    situation: "Disponible",

    total_area: 40,
    antiquity: 1,
    operation: "Venta",
    owner: "Schiaffino",
  },
  {
    type: "Oficina",
    address: "avenida central 123",
    spaces: 5,
    price: 3,
    pictures: [
      {
        img: "https://static.tokkobroker.com/water_pics/17846430131435450663802764701632463767729046383836463334866695832242741911680.jpg",
      },
    ],
    floors: 4,
    covered_area: 3,
    bathroom: 2,
    bedroom: 0,
    furnished: true,
    description: "Oficina moderna en zona céntrica",
    situation: "Disponible",
    total_area: 4,
    antiquity: 3,
    operation: "Alquiler",
    owner: "María López",
  },
  {
    type: "Vivienda",
    address: "calle residencial 456",
    spaces: 4,
    price: 5,
    pictures: [
      {
        img: "https://static.tokkobroker.com/water_pics/105179491635416062046595029431870343293087641099735041783583063934609465411958.jpg",
      },
    ],
    floors: 2,
    covered_area: 3,
    bathroom: 2,
    bedroom: 3,
    furnished: false,
    description: "Apartamento acogedor en zona tranquila",
    situation: "Reservado",
    total_area: 5,
    antiquity: 4,
    operation: "Venta",
    owner: "Juan Pérez",
  },
  {
    type: "Local",
    address: "calle comercial 789",
    spaces: 2,
    price: 3,
    pictures: [
      {
        img: "https://static.tokkobroker.com/water_pics/30999149494816486478919015056718714507359439308603906076688768532749798650730.jpg",
      },
    ],
    floors: 1,
    covered_area: 2,
    bathroom: 1,
    bedroom: 0,
    furnished: true,
    description: "Local en zona comercial de alto flujo",
    situation: "Disponible",
    total_area: 3,
    antiquity: 1,
    operation: "Alquiler",
    owner: "Luisa Rodríguez",
  },
  {
    type: "Industria",
    address: "calle industrial 987",
    spaces: 10,
    price: 8,
    pictures: [
      {
        img: "https://static.tokkobroker.com/water_pics/72894166417316665192821485727387117555147100617543642279941753163186345981009.jpg",
      },
    ],
    floors: 1,
    covered_area: 6,
    bathroom: 3,
    bedroom: 0,
    furnished: false,
    description: "Amplia nave industrial en zona estratégica",
    situation: "Disponible",
    total_area: 12,
    antiquity: 5,
    operation: "Venta",
    owner: "Ricardo Gómez",
  },
  {
    type: "Vivienda",
    address: "calle residencial 789",
    spaces: 3,
    price: 4,
    pictures: [
      {
        img: "https://static.tokkobroker.com/water_pics/54041480597218751892234760147460969365051802427537328121401754377569397885524.jpg",
      },
    ],
    floors: 1,
    covered_area: 2,
    bathroom: 2,
    bedroom: 2,
    furnished: true,
    description: "Casa familiar con jardín y terraza",
    situation: "Disponible",
    total_area: 4,
    antiquity: 6,
    operation: "Alquiler",
    owner: "Marcela Torres",
  },
  {
    type: "Oficina",
    address: "avenida principal 456",
    spaces: 6,
    price: 5,
    pictures: [
      {
        img: "https://static.tokkobroker.com/water_pics/107084436526004856054109398742782845838285764777260065404064546762174305823375.jpg",
      },
    ],
    floors: 8,
    covered_area: 5,
    bathroom: 2,
    bedroom: 0,
    furnished: true,
    description: "Amplia oficina en edificio corporativo",
    situation: "Disponible",
    total_area: 7,
    antiquity: 3,
    operation: "Venta",
    owner: "Andrés Martínez",
  },
  {
    type: "Local",
    address: "calle comercial 123",
    spaces: 1,
    price: 2,
    pictures: [{ img: "direciondelaimagen8.jpg" }],
    floors: 1,
    covered_area: 1,
    bathroom: 1,
    bedroom: 0,
    furnished: false,
    description: "Local en zona comercial de alto tráfico",
    situation: "Disponible",
    total_area: 2,
    antiquity: 2,
    operation: "Alquiler",
    owner: "Laura Díaz",
  },
  {
    type: "Industria",
    address: "calle industrial 789",
    spaces: 12,
    price: 10,
    pictures: [{ img: "direciondelaimagen9.jpg" }],
    floors: 1,
    covered_area: 8,
    bathroom: 4,
    bedroom: 0,
    furnished: false,
    description: "Nave industrial con acceso para camiones",
    situation: "Disponible",
    total_area: 14,
    antiquity: 8,
    operation: "Venta",
    owner: "Pablo Sánchez",
  },
  {
    type: "Vivienda",
    address: "calle residencial 123",
    spaces: 2,
    price: 3,
    pictures: [{ img: "direciondelaimagen10.jpg" }],
    floors: 1,
    covered_area: 2,
    bathroom: 1,
    bedroom: 1,
    furnished: true,
    description: "Apartamento céntrico con vistas panorámicas",
    situation: "Reservado",
    total_area: 3,
    antiquity: 3,
    operation: "Venta",
    owner: "Carolina Gutiérrez",
  },
  {
    type: "Vivienda",
    address: "san juan 2764",
    spaces: 3,
    price: 2,
    pictures: [{ img: "direciondelaimagen.jpg" }],
    floors: 3,
    covered_area: 2,
    bathroom: 4,
    bedroom: 5,
    furnished: true,
    description: "esta es una descripcion",
    situation: "Disponible",
    total_area: 3,
    antiquity: 2,
    operation: "Alquiler",
    owner: "Azul schiaffino",
  },
  {
    type: "Vivienda",
    address: "calle principal 987",
    spaces: 4,
    price: 3,
    pictures: [{ img: "direciondelaimagen5.jpg" }],
    floors: 2,
    covered_area: 3,
    bathroom: 2,
    bedroom: 3,
    furnished: true,
    description: "Casa familiar con jardín",
    situation: "Disponible",
    total_area: 5,
    antiquity: 5,
    operation: "Venta",
    owner: "Laura Martínez",
  },
  {
    type: "Oficina",
    address: "avenida comercial 456",
    spaces: 8,
    price: 6,
    pictures: [{ img: "direciondelaimagen6.jpg" }],
    floors: 10,
    covered_area: 5,
    bathroom: 3,
    bedroom: 0,
    furnished: true,
    description: "Oficina espaciosa con hermosa vista",
    situation: "Disponible",
    total_area: 8,
    antiquity: 2,
    operation: "Alquiler",
    owner: "Carlos López",
  },
  {
    type: "Local",
    address: "calle comercial 789",
    spaces: 1,
    price: 2,
    pictures: [{ img: "direciondelaimagen7.jpg" }],
    floors: 1,
    covered_area: 2,
    bathroom: 1,
    bedroom: 0,
    furnished: false,
    description: "Local en zona de alto tráfico",
    situation: "Reservado",
    total_area: 3,
    antiquity: 3,
    operation: "Venta",
    owner: "Ana Rodríguez",
  },
  {
    type: "Industria",
    address: "calle industrial 123",
    spaces: 12,
    price: 10,
    pictures: [{ img: "direciondelaimagen8.jpg" }],
    floors: 1,
    covered_area: 8,
    bathroom: 4,
    bedroom: 0,
    furnished: true,
    description: "Nave industrial con amplios espacios de almacenamiento",
    situation: "Disponible",
    total_area: 15,
    antiquity: 6,
    operation: "Alquiler",
    owner: "Javier González",
  },
  {
    type: "Vivienda",
    address: "calle residencial 654",
    spaces: 5,
    price: 4,
    pictures: [{ img: "direciondelaimagen9.jpg" }],
    floors: 2,
    covered_area: 4,
    bathroom: 3,
    bedroom: 4,
    furnished: true,
    description: "Casa amplia con jardín y piscina",
    situation: "Disponible",
    total_area: 6,
    antiquity: 7,
    operation: "Venta",
    owner: "Martín Pérez",
  },
  {
    type: "Oficina",
    address: "avenida principal 789",
    spaces: 6,
    price: 5,
    pictures: [{ img: "direciondelaimagen10.jpg" }],
    floors: 8,
    covered_area: 6,
    bathroom: 2,
    bedroom: 0,
    furnished: false,
    description: "Oficina moderna en edificio corporativo",
    situation: "Disponible",
    total_area: 9,
    antiquity: 4,
    operation: "Venta",
    owner: "Sofía Ramírez",
  },
  {
    type: "Vivienda",
    address: "calle residencial 123",
    spaces: 3,
    price: 4,
    pictures: [{ img: "direciondelaimagen11.jpg" }],
    floors: 2,
    covered_area: 3,
    bathroom: 2,
    bedroom: 2,
    furnished: true,
    description: "Amplio apartamento en zona residencial",
    situation: "Disponible",
    total_area: 4,
    antiquity: 5,
    operation: "Venta",
    owner: "Alejandro Gómez",
  },
  {
    type: "Oficina",
    address: "avenida principal 789",
    spaces: 4,
    price: 6,
    pictures: [{ img: "direciondelaimagen12.jpg" }],
    floors: 5,
    covered_area: 4,
    bathroom: 2,
    bedroom: 0,
    furnished: true,
    description: "Oficina moderna en edificio de lujo",
    situation: "Disponible",
    total_area: 5,
    antiquity: 3,
    operation: "Alquiler",
    owner: "María Rodríguez",
  },
  {
    type: "Local",
    address: "calle comercial 456",
    spaces: 2,
    price: 3,
    pictures: [{ img: "direciondelaimagen13.jpg" }],
    floors: 1,
    covered_area: 2,
    bathroom: 1,
    bedroom: 0,
    furnished: false,
    description: "Local en zona comercial de alto movimiento",
    situation: "Reservado",
    total_area: 3,
    antiquity: 2,
    operation: "Venta",
    owner: "Carlos Sánchez",
  },
  {
    type: "Industria",
    address: "calle industrial 123",
    spaces: 8,
    price: 9,
    pictures: [{ img: "direciondelaimagen14.jpg" }],
    floors: 1,
    covered_area: 6,
    bathroom: 3,
    bedroom: 0,
    furnished: true,
    description: "Nave industrial con amplio espacio de almacenamiento",
    situation: "Disponible",
    total_area: 10,
    antiquity: 6,
    operation: "Venta",
    owner: "Laura Gómez",
  },
  {
    type: "Vivienda",
    address: "calle residencial 789",
    spaces: 4,
    price: 5,
    pictures: [{ img: "direciondelaimagen15.jpg" }],
    floors: 2,
    covered_area: 3,
    bathroom: 2,
    bedroom: 3,
    furnished: false,
    description: "Casa moderna con jardín y piscina",
    situation: "Disponible",
    total_area: 5,
    antiquity: 4,
    operation: "Alquiler",
    owner: "Juan Torres",
  },
  {
    type: "Oficina",
    address: "avenida principal 123",
    spaces: 6,
    price: 7,
    pictures: [{ img: "direciondelaimagen16.jpg" }],
    floors: 7,
    covered_area: 5,
    bathroom: 2,
    bedroom: 0,
    furnished: true,
    description: "Oficina con diseño vanguardista",
    situation: "Reservado",
    total_area: 7,
    antiquity: 5,
    operation: "Venta",
    owner: "Sofía López",
  },
  {
    type: "Local",
    address: "calle comercial 789",
    spaces: 3,
    price: 4,
    pictures: [{ img: "direciondelaimagen17.jpg" }],
    floors: 1,
    covered_area: 2,
    bathroom: 1,
    bedroom: 0,
    furnished: false,
    description: "Local en zona comercial de alta visibilidad",
    situation: "Disponible",
    total_area: 3,
    antiquity: 2,
    operation: "Alquiler",
    owner: "Pedro Rodríguez",
  },
  {
    type: "Industria",
    address: "calle industrial 456",
    spaces: 10,
    price: 8,
    pictures: [{ img: "direciondelaimagen18.jpg" }],
    floors: 1,
    covered_area: 7,
    bathroom: 3,
    bedroom: 0,
    furnished: true,
    description: "Amplia nave industrial con acceso para camiones",
    situation: "Disponible",
    total_area: 12,
    antiquity: 9,
    operation: "Venta",
    owner: "Ana Martínez",
  },
  {
    type: "Vivienda",
    address: "calle residencial 456",
    spaces: 2,
    price: 3,
    pictures: [{ img: "direciondelaimagen19.jpg" }],
    floors: 1,
    covered_area: 2,
    bathroom: 1,
    bedroom: 1,
    furnished: false,
    description: "Apartamento acogedor con excelente ubicación",
    situation: "Disponible",
    total_area: 3,
    antiquity: 3,
    operation: "Venta",
    owner: "Lucía Torres",
  },
  {
    type: "Oficina",
    address: "avenida principal 456",
    spaces: 8,
    price: 9,
    pictures: [{ img: "direciondelaimagen20.jpg" }],
    floors: 6,
    covered_area: 7,
    bathroom: 3,
    bedroom: 0,
    furnished: true,
    description: "Oficina amplia y luminosa en edificio corporativo",
    situation: "Reservado",
    total_area: 9,
    antiquity: 7,
    operation: "Alquiler",
    owner: "Mario Gómez",
  },
  {
    type: "Vivienda",
    address: "calle residencial 1",
    spaces: 3,
    price: 200000,
    pictures: [{ img: "img1.jpg" }],
    floors: 2,
    covered_area: 120,
    bathroom: 2,
    bedroom: 3,
    furnished: true,
    description: "Hermosa casa en zona residencial",
    situation: "Disponible",
    total_area: 300,
    antiquity: 5,
    operation: "Venta",
    owner: "Juan Perez",
  },
  {
    type: "Oficina",
    address: "avenida principal 2",
    spaces: 5,
    price: 1500,
    pictures: [{ img: "img2.jpg" }],
    floors: 4,
    covered_area: 80,
    bathroom: 1,
    bedroom: 0,
    furnished: false,
    description: "Oficina moderna en edificio corporativo",
    situation: "Disponible",
    total_area: 100,
    antiquity: 2,
    operation: "Alquiler",
    owner: "Maria Rodriguez",
  },
  {
    type: "Local",
    address: "calle comercial 3",
    spaces: 1,
    price: 500,
    pictures: [{ img: "img3.jpg" }],
    floors: 1,
    covered_area: 50,
    bathroom: 1,
    bedroom: 0,
    furnished: true,
    description: "Local en zona comercial con alto tránsito",
    situation: "Disponible",
    total_area: 80,
    antiquity: 1,
    operation: "Alquiler",
    owner: "Pedro Sanchez",
  },
  {
    type: "Industria",
    address: "calle industrial 4",
    spaces: 10,
    price: 500000,
    pictures: [{ img: "img4.jpg" }],
    floors: 1,
    covered_area: 500,
    bathroom: 2,
    bedroom: 0,
    furnished: false,
    description: "Nave industrial con amplio espacio de almacenamiento",
    situation: "Disponible",
    total_area: 1000,
    antiquity: 10,
    operation: "Venta",
    owner: "Laura Gomez",
  },
  {
    type: "Vivienda",
    address: "calle residencial 5",
    spaces: 4,
    price: 300000,
    pictures: [{ img: "img5.jpg" }],
    floors: 2,
    covered_area: 150,
    bathroom: 3,
    bedroom: 4,
    furnished: true,
    description: "Hermoso chalet con jardín y piscina",
    situation: "Disponible",
    total_area: 400,
    antiquity: 8,
    operation: "Venta",
    owner: "Carlos Fernandez",
  },
  {
    type: "Oficina",
    address: "avenida principal 6",
    spaces: 3,
    price: 1000,
    pictures: [{ img: "img6.jpg" }],
    floors: 3,
    covered_area: 100,
    bathroom: 2,
    bedroom: 0,
    furnished: true,
    description: "Oficina amplia y luminosa en edificio corporativo",
    situation: "Disponible",
    total_area: 150,
    antiquity: 4,
    operation: "Alquiler",
    owner: "Ana Martinez",
  },
  {
    type: "Local",
    address: "calle comercial 7",
    spaces: 2,
    price: 800,
    pictures: [{ img: "img7.jpg" }],
    floors: 1,
    covered_area: 70,
    bathroom: 1,
    bedroom: 0,
    furnished: false,
    description: "Local en zona céntrica con buena visibilidad",
    situation: "Disponible",
    total_area: 100,
    antiquity: 3,
    operation: "Alquiler",
    owner: "Daniel Lopez",
  },
  {
    type: "Industria",
    address: "calle industrial 8",
    spaces: 15,
    price: 800000,
    pictures: [{ img: "img8.jpg" }],
    floors: 2,
    covered_area: 1000,
    bathroom: 4,
    bedroom: 0,
    furnished: true,
    description: "Amplia nave industrial con excelente ubicación",
    situation: "Disponible",
    total_area: 2000,
    antiquity: 15,
    operation: "Venta",
    owner: "Luis Ramirez",
  },
  {
    type: "Vivienda",
    address: "calle residencial 9",
    spaces: 2,
    price: 250000,
    pictures: [{ img: "img9.jpg" }],
    floors: 1,
    covered_area: 90,
    bathroom: 1,
    bedroom: 2,
    furnished: false,
    description: "Apartamento luminoso con vista al mar",
    situation: "Disponible",
    total_area: 120,
    antiquity: 6,
    operation: "Venta",
    owner: "Martha Suarez",
  },
  {
    type: "Oficina",
    address: "avenida principal 10",
    spaces: 6,
    price: 1200,
    pictures: [{ img: "img10.jpg" }],
    floors: 5,
    covered_area: 200,
    bathroom: 2,
    bedroom: 0,
    furnished: true,
    description: "Oficina en edificio de categoría con seguridad 24/7",
    situation: "Disponible",
    total_area: 250,
    antiquity: 5,
    operation: "Alquiler",
    owner: "Roberto Castro",
  },
  {
    type: "Vivienda",
    address: "calle residencial 11",
    spaces: 4,
    price: 350000,
    pictures: [{ img: "img11.jpg" }],
    floors: 2,
    covered_area: 160,
    bathroom: 2,
    bedroom: 3,
    furnished: true,
    description: "Amplia casa con jardín y área de recreación",
    situation: "Disponible",
    total_area: 400,
    antiquity: 10,
    operation: "Venta",
    owner: "Pedro Rodriguez",
  },
  {
    type: "Oficina",
    address: "avenida principal 12",
    spaces: 3,
    price: 1100,
    pictures: [{ img: "img12.jpg" }],
    floors: 4,
    covered_area: 120,
    bathroom: 1,
    bedroom: 0,
    furnished: false,
    description: "Oficina moderna en edificio de negocios",
    situation: "Disponible",
    total_area: 150,
    antiquity: 3,
    operation: "Alquiler",
    owner: "Luisa Gomez",
  },
  {
    type: "Local",
    address: "calle comercial 13",
    spaces: 1,
    price: 600,
    pictures: [{ img: "img13.jpg" }],
    floors: 1,
    covered_area: 50,
    bathroom: 1,
    bedroom: 0,
    furnished: true,
    description: "Local en zona comercial con alto tránsito",
    situation: "Disponible",
    total_area: 80,
    antiquity: 2,
    operation: "Alquiler",
    owner: "Marcela Fernandez",
  },
  {
    type: "Industria",
    address: "calle industrial 14",
    spaces: 12,
    price: 900000,
    pictures: [{ img: "img14.jpg" }],
    floors: 2,
    covered_area: 800,
    bathroom: 3,
    bedroom: 0,
    furnished: false,
    description: "Nave industrial con amplio espacio de almacenamiento",
    situation: "Disponible",
    total_area: 1500,
    antiquity: 12,
    operation: "Venta",
    owner: "Carlos Gomez",
  },
  {
    type: "Vivienda",
    address: "calle residencial 15",
    spaces: 3,
    price: 280000,
    pictures: [{ img: "img15.jpg" }],
    floors: 1,
    covered_area: 110,
    bathroom: 2,
    bedroom: 3,
    furnished: true,
    description: "Casa con jardín y piscina en zona tranquila",
    situation: "Disponible",
    total_area: 350,
    antiquity: 7,
    operation: "Venta",
    owner: "Sofia Ramirez",
  },
  {
    type: "Oficina",
    address: "avenida principal 16",
    spaces: 4,
    price: 1200,
    pictures: [{ img: "img16.jpg" }],
    floors: 3,
    covered_area: 150,
    bathroom: 2,
    bedroom: 0,
    furnished: true,
    description: "Oficina con excelente ubicación y comodidades",
    situation: "Disponible",
    total_area: 180,
    antiquity: 4,
    operation: "Alquiler",
    owner: "Juan Fernandez",
  },
  {
    type: "Local",
    address: "calle comercial 17",
    spaces: 1,
    price: 700,
    pictures: [{ img: "img17.jpg" }],
    floors: 1,
    covered_area: 60,
    bathroom: 1,
    bedroom: 0,
    furnished: false,
    description: "Local en centro comercial con gran visibilidad",
    situation: "Disponible",
    total_area: 90,
    antiquity: 3,
    operation: "Alquiler",
    owner: "Ana Gonzalez",
  },
  {
    type: "Industria",
    address: "calle industrial 18",
    spaces: 20,
    price: 1200000,
    pictures: [{ img: "img18.jpg" }],
    floors: 3,
    covered_area: 1500,
    bathroom: 5,
    bedroom: 0,
    furnished: true,
    description: "Complejo industrial con múltiples galpones",
    situation: "Disponible",
    total_area: 3000,
    antiquity: 20,
    operation: "Venta",
    owner: "Miguel Torres",
  },
  {
    type: "Vivienda",
    address: "calle residencial 19",
    spaces: 5,
    price: 420000,
    pictures: [{ img: "img19.jpg" }],
    floors: 2,
    covered_area: 180,
    bathroom: 3,
    bedroom: 4,
    furnished: false,
    description: "Casa amplia con patio y parrillero",
    situation: "Disponible",
    total_area: 500,
    antiquity: 9,
    operation: "Venta",
    owner: "Laura Medina",
  },
  {
    type: "Oficina",
    address: "avenida principal 20",
    spaces: 8,
    price: 1500,
    pictures: [{ img: "img20.jpg" }],
    floors: 6,
    covered_area: 250,
    bathroom: 3,
    bedroom: 0,
    furnished: true,
    description: "Oficina en edificio corporativo de lujo",
    situation: "Disponible",
    total_area: 300,
    antiquity: 6,
    operation: "Alquiler",
    owner: "Javier Perez",
  },
];
